experiment_name: "deepfake_baseline_xception"
description: "Baseline configuration using Xception backbone, one ReLU dense layer, and facial coordinate integration."
seed : 42
data:
  batch_size: 16
  num_workers: 4
model:
  backbone: "xception"
  pretrained: true
  freeze_backbone: false
  classifier_head:
    type: "1_layer_dense"
    layers:
      - type: "Dense"
        units: 512
        activation: "relu"
        dropout: 0.5
  facial_coordinates:
    enabled: true
    fusion_method: "concatenate" # Nối vector tọa độ vào trước lớp Dense thứ 1

optimization:
  optimizer: "AdamW"
  learning_rate: 0.0001
  weight_decay: 0.01
  loss_function: "CrossEntropyLoss" 
  scheduler: # finetune LR của model
    type: "ReduceLROnPlateau"
    mode: "min"
    factor: 0.1 # sau khi qua mức <patience> epochs mà loss ko giảm thì LR = LR*factor
    patience: 2
  early_stopping:
    patience: 5
    monitor: "val_loss"
  max_epochs: 20

cross_validation:
  strategy: "StratifiedKFold"
  n_splits: 5
  shuffle: true

metrics:
  - "accuracy"
  - "f1_score"
  - "roc_auc"

result_paths: 'results\baseline.csv'
checkpoint_dir: 'results\checkpoints'